name: Scrape
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -r .github/workflows/requirements.txt
        
      - name: Run python script
        run: python3 .github/workflows/scrape.py

