name: Scrape Timetable pdf from Wikamp and convert it to JSON file
on:
  schedule:
    - cron: "0 12 * 9-12 *"  # Wrzesień - Grudzień
    - cron: "0 12 * 1-6 *"   # Styczeń - Czerwiec
  workflow_dispatch:
env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Python imports
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt

      - name: Run python script
        run: python3 .github/workflows/scrape.py

      - name: Commit changes
        run: |
          git config --local user.email "github-actions"
          git config --local user.name "github-actions"
          git add --all
          git commit -m "Refresh Scraped Data" || exit 0

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
